# Generated by Django 5.0.7 on 2024-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='version',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(),
        ),
    ]
