# Generated by Django 4.2.11 on 2024-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('netbox_certificate_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='device',
        ),
        migrations.AddField(
            model_name='certificate',
            name='devices',
            field=models.ManyToManyField(blank=True, to='dcim.device'),
        ),
    ]
