# Generated by Django 5.0.7 on 2024-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0002_remove_certificate_device_certificate_devices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='valid_to',
        ),
    ]
