# Generated by Django 5.0.7 on 2024-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_certificate_management', '0002_remove_certificate__depth'),
        ('virtualization', '0038_virtualdisk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('serial_number', 'issuer_name'), name='unique_serial_issuer'),
        ),
    ]
