# Generated by Django 5.0.7 on 2024-08-12 21:11

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0003_certificate_unique_serial_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='netbox_certificate_management.certificate'),
        ),
    ]
