# Generated by Django 5.1.7 on 2025-03-25 09:38

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0007_alter_certificate_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='subject', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='netbox_certificate_management.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(default='subject', max_length=100),
            preserve_default=False,
        ),
    ]
