# Generated by Django 5.1.7 on 2025-03-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0008_certificate_description_certificate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='slug',
        ),
    ]
