# Generated by Django 5.1.7 on 2025-03-25 09:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0009_remove_certificate_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='certificate',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
