# Generated by Django 5.1.7 on 2025-03-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificate_management', '0010_alter_certificate_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='certificate',
            managers=[
            ],
        ),
    ]
